<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>the web stack</title>
    <link rel="stylesheet" href="style.min.css">
</head>
<body ng-app="myApp">
<div class="container">
    <div class="jumbotron">
        <h1>The Web Stack</h1>
        <p>A Stack based on Slim Framework and Angular.js to build efficient web applications</p>
    </div>
    <div class="row">
        <div ng-view></div>
    </div>
</div>
<script src="app.min.js"></script>
</body>
</html>
