<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>Nuragio</title>
    <link rel="stylesheet" href="minified/style.min.css">
</head>
<body ng-app="myApp">
    <header class="navbar navbar-default navbar-fixed-top navbar-inner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-3" ng-click="isCollapsed = !isCollapsed">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand visible-xs" href="/">Home</a>
            </div>
            <nav class="hidden-xs">
                <ul  class="nav navbar-nav">
                    <li>
                        <a class="navbar-brand" href="/">home</a>
                    </li>
                </ul>
            </nav>
            <nav uib-collapse="!isCollapsed">
                <ul class="nav navbar-nav">
                    <li><a href="/" ng-click="isCollapsed = !isCollapsed">Home</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <div class="jumbotron">
        <div class="container">
            <h1>Nuragio</h1>
            <p>A Stack based on Slim Framework and Angular.js to build efficient web applications</p>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div ng-view></div>
        </div>
    </div>
<script src="minified/app.min.js"></script>
</body>
</html>
